### ISSUE TITLE
VmwrResult custom Hook을 js-doc으로 관리한다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#106]
### ⚠️Issue
- VmwrResult custom Hook을 js-doc으로 관리한다.

### ✏️Task
- [x] generateResultContent.js를 js-doc으로 관리한다.
  - [ ] generateResultContent를 생각한 이유와 사고 방식을 작성해주세요.
- [x] VmwrResult custom Hook을 js-doc으로 관리한다.

### 🗓Next Task
-
