### ISSUE TITLE
ver.2.0.0을 위해 개발환경을 세팅한다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#111]
# ⚠️Issue
- ver.2.0.0을 위해 개발환경을 세팅한다.

# ✏️Task
- [x] 패키지 매니저를 yarn으로 한다.
- [x] webpack으로 react 환경을 구축한다.
  - [x] copy-webpack-plugin
  - [x] mini-css-extract-plugin
  - ~[ ] terser-webpack-pulgin~
  - [x] svgo-loader
- [x] babel을 설정한다.
- [x] ESbuild를 설정한다.
---
## 🚮legacy
- ~Vite로 React를 구현한다.~
- ~[ ] 기존 eslint와 prettier 규칙을 ~유지한다.~ 수정한다.~
  - ~[ ] pretteir를 따로 분리해서 관리한다.~
- ~[ ] Mono-repo로 구현한다.~
  - ~[ ] Supabase Edge Function을 관리하는 server-less 디렉토리를 추가한다.~
  - ~[ ] server-less 디렉토리에 Supabase SDK를 설치한다.~
---

# Reference
- 🔗[webpack에 필요한 5가지 plugin](https://kagrin97-blog.vercel.app/other/webpack-basic-plugin 'webpack에 필요한 5가지 plugin')

#
### 프로젝트 목적
- 반응형으로 구현을 한다.
- server-less를 활용해서 백엔드의 부재를 극복한다.
- reactQeury를 사용해서 통신을 시도한다.
- ESbuild를 찾아보고 프로젝트에 필요한지 점검을 해본다.
  - Webpack을 dev-server 용도로 사용하고, esbuild를 build 스크립트로 활용하는 방식으로 세팅한다.
- typescript 환경으로 개발을 한다.
- webpack과 babel로 react를 세팅함으로 webpack과 babel을 학습한다.
- 이미지를 최적화한다.
- Optimistic UI와 RoleBack UI를 구현함으로 하이브리드 방식을 구현한다.
- ~workspace로 react와 RN, server 디렉토리를 구현한다.~
- ssr로 구현을 한다.
---

<details>
  <summary>환경 세팅 과정</summary>

# webpack으로 react 환경 세팅

### React 및 ReactDOM 설치
```
yarn add react@18 react-dom@18
```

### Webpack 및 Webpack 관련 패키지 설치 (개발 의존성)
```
yarn add -D webpack webpack-cli webpack-dev-server html-webpack-plugin clean-webpack-plugin 
yarn add -D babel-loader @babel/core @babel/preset-env @babel/preset-react css-loader style-loader file-loader
```

### TypeScript 설치
```
yarn add -D typescript @babel/preset-typescript ts-loader @types/react@18 @types/react-dom@18
```
---
### Webpack 설정
```
// webpack.config.js
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const { CleanWebpackPlugin } = require("clean-webpack-plugin");

module.exports = {
  mode: "development",
  entry: "./src/index.tsx",
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "bundle.js",
  },
  devServer: {
    static: {
      directory: path.resolve(__dirname, "dist"),
    },
    port: 3000,
    hot: true,
    open: true,
    historyApiFallback: true,
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx|ts|tsx)$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
        },
      },
      {
        test: /\.css$/,
        use: ["style-loader", "css-loader"],
      },
      {
        test: /\.(png|jpg|jpeg|gif|svg)$/,
        type: "asset/resource",
      },
    ],
  },
  resolve: {
    extensions: [".js", ".jsx", ".ts", ".tsx"],
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: "./public/index.html",
    }),
    new CleanWebpackPlugin(),
  ],
};

```

### Babel 설정
```
// .babelrc
{
  "presets": [
    "@babel/preset-env",
    ["@babel/preset-react", { "runtime": "automatic" }],
    "@babel/preset-typescript"
  ]
}
// `["@babel/preset-react", { "runtime": "automatic" }],`는 React 18버전에 맞게 `import react`와 `React.FC`타입 지정을 생략할 수 있게 하는 속성 값 설정이다.
```

### 현재 package.json
```
// package.json
  "dependencies": {
    "react": "18",
    "react-dom": "18"
  },
  "devDependencies": {
    "@babel/core": "^7.26.7",
    "@babel/preset-env": "^7.26.7",
    "@babel/preset-react": "^7.26.3",
    "@babel/preset-typescript": "^7.26.0",
    "@types/react": "18",
    "@types/react-dom": "18",
    "babel-loader": "^9.2.1",
    "clean-webpack-plugin": "^4.0.0",
    "css-loader": "^7.1.2",
    "file-loader": "^6.2.0",
    "html-webpack-plugin": "^5.6.3",
    "style-loader": "^4.0.0",
    "ts-loader": "^9.5.2",
    "typescript": "^5.7.3",
    "webpack": "^5.97.1",
    "webpack-cli": "^6.0.1",
    "webpack-dev-server": "^5.2.0"
  }
```
### ESbuild 설치

```
yarn add -D esbuild esbuild-loader
```

### TypeScript *.d.ts 파일 설정
```
// global.d.ts
declare module "*.css";
declare module "*.scss";
declare module "*.sass";

```

</details>

---

### 🗓Next Task
-
