### ISSUE TITLE
server-less로 네편현답(posting) api를 구현한다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#119]
### ⚠️Issue
- server-less로 네편현답(posting) api를 구현한다.

### ✏️Task
- [x] server-less로 네편현답(posting) api를 구현한다.
  - [x] 전체 게시글 조회 - GET
    - [x] 게시글 세부 조회 qna/info - GET
  - [x] 인기 게시글 조회 - GET
    - [x] 게시글 세부 조회 qna/info - GET
  - [x] 게시글 등록 - POST
#
- [x] server-less로 북마크(bookmarks) api를 구현한다.
  - [x] 게시글 책갈피(북마크) 조회 - GET
  - [x] 게시글 책갈피(북마크) 추가 - POST
  - [x] 게시글 책갈피(북마크) 해제 - DELETE

### 🗓Next Task
-
