### ISSUE TITLE
공지사항(Notaion) 페이지 CSS 점검 및 수정

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#20]
### ⚠️Issue
- 로컬 프로젝트  내에 문제가 있어 git clone 재시도 후 CSS 점검

### ✏️Task
- [x] git clone 이후 프로젝트를 재시도 해본다.
- [x] Notation페이지에 CSS 문제가 있어 수정
- [x] Notion페이지에 container 클래스 추가 필요
- [x] ContractReviw 페이지 HTML 및 CSS 적용

### 🗓Next Task
- [x] ContractReviw 페이지 디테일 HTML 및 CSS 적용
