### ISSUE TITLE
Mocking을 위한 더미데이터 가공

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#21]
### ⚠️Issue
- BE 없이 Mocking을 위한 작업

### ✏️Task
- [x] 모킹할 페이지를 제작한다.
- [x] 더미데이터를 실제 데이터와 유사하게 json형태로 구현한다.

### 🗓Next Task
- [x] 추가해야할 더미 데이터를 확인해본다.
- [x] 모킹할 페이지에서 get을 통해 데이터를 map으로 나열한다.
