### ISSUE TITLE
내 계약서 검토(ContractReview)페이지 디테일 HTML 및 CSS 적용

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#23]
### ⚠️Issue
- ContractReviw 페이지에 보이는 세부적인 부분들을 html로 재 그룹화 하고 css를 적용한다.
  - hurskyNav 라이브러를 사용한다.

### ✏️Task
- [x] ContractReviw 페이지 디테일 HTML 및 CSS 적용
- [x] 표준근로 계약 list부분을 클릭 했을 때 표준근로 계약의 설명란 부분 display 값이 none이 되었다 flex가 되었다 할 수 있는 기능을 삽입한다.

### 🗓Next Task
- [x] 모킹된 데이터를 가지고 페이지에 직접 적용을 해본다.
- [x] 백엔드와의 통신을 위해 proxy를 학습하고 코드를 다시 살펴 본다.

**Comment by 4BFC** [comment]
🐞Erro Report
```
  (node:19596) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
  (Use `node --trace-deprecation ...` to show where the warning was created)
  (node:19596) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
  Starting the development server...
  
  Compiled with warnings.
```

최근 React에서 기존 `webpack-dev-server`의 설정 옵션이 변경됨에 따라 발생한 오류이다. webpack-dev-server의 일부 설정이 이전 버전에서는 onBeforeSetupMiddleware와 onAfterSetupMiddleware 옵션으로 미들웨어를 구성했지만 최신 버전에서는 이를 setupMiddlewares라는 옵션으로 대체 됨에 따라 이를 해결하기 위해서는 두가지 방안이 있는데 첫번째는 `craco`를 사용해서 간접적으로 `webpack.config`를 수정해야한다.
  ```
    module.exports = {
      // ... other webpack config
      devServer: {
        // 기존의 deprecated 옵션을 제거합니다.
        // onBeforeSetupMiddleware: function (devServer) {
        //   devServer.app.get('/some/path', function (req, res) {
        //     res.json({ custom: 'response' });
        //   });
        // },
        // onAfterSetupMiddleware: function (devServer) {
        //   console.log('Setup complete');
        // },
    
        // 새로운 방식으로 대체합니다.
        setupMiddlewares: (middlewares, devServer) => {
          devServer.app.get('/some/path', function (req, res) {
            res.json({ custom: 'response' });
          });
    
          console.log('Setup complete');
          return middlewares;
        },
      },
    };
  ```
마지막으로 craco와 같은 라이브러리를 사용하지 않는다면 webpack-dev-server를 최신 버전으로 업데이트하거나 react-scripts를 업데이트하면 된다.
  ```
    npm install webpack-dev-server@latest
  ```
