### ISSUE TITLE
전역상태관리를 위해 테스트를 해본다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#26]
### ⚠️Issue
- useState를 전역상태관리 할 수 있게 코드와 디렉토리 구조를 커스텀해본다.

### ✏️Task
- [x] contextAPI를 활용해서 useState를 전역상태관리할 수 있게 코드를 작성해본다.
- [x] 상황에 따라 eslint 코드를 편집한다.
- [x] eslint의 자동 정렬을 위한 .vscode/settings.json 파일을 생성한다.
- [x] build 해본다.

### 🗓Next Task
- 테스트가 성공시 디렉토리 구조를 새롭게 구상하고 팀원과 논의해 본다.
