### ISSUE TITLE
내 근로 정리(WorkArrangement)페이지 css를 마무리한다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#31]
### ⚠️Issue
- 내 근로 정리(WorkArrangement)페이지 css를 마무리한다.

### ✏️Task
- [x] 내 근로 정리(WorkArrangement)페이지 css를 마무리한다.
  - ~[x] a태그는 링크로 대체~
  - [x] padding과 margin
  - [x] justify-content
- [x] 컴포넌트화 할 수 있는 UI/UX를 생각하면서 코드를 작성한다.
  - [x] WorkArrangement result 부분 다시 작업
    - [x] id, wa-option 컴포넌트화 필요
    - [x] class, wa-result 컴포넌트화 필요
      - [x] 이 둘의 컴포넌트 분리 시 부모관계 유의 할 필요 있음
- [x] 팀원과 협의된 직관적인 디렉토리 구조를 위해 디렉토리 구조 변경

### 🗓Next Task
- 컴포넌트화를 준비한다.
- [x] #32 
- [x] #39
- API를 위한 훅을 제작한다.
