### ISSUE TITLE
내 근로 살펴보기(ViewMyWork) 페이지 css를 작성한다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#32]
### ⚠️Issue
  - 내 근로 살펴보기(ViewMyWork) 페이지 html을 작성한다.
  - 컴포넌트로 구성할 영역을 생각하고 컴포넌트로 나눈다.
    - 재활용되는 컴포넌트 네이밍은 `component`라는 단수로 키워드를 넣어야한다. (ex. ViewMyWorkOption.component.jsx)
      - option 영역
      - input 영역
- 내 근로 살펴보기(ViewMyWork) 페이지 css룰 작성한다.
- component를 사용해서 영역을 분리한다.
  - props를 사용해서 각기 다르게 코드를 구성할 수 있게 짠다.
  - input 부분의 스타일이~ 삼항연산~ _(eslint 규칙에 의해 삼항연산 불가 이에 if문으로 변경)_ if문을 사용해서 전달받은 props에 따라 값이 UI가 동적으로 변할 수 있게 코드를 작성한다.
  - 배열 객체를 생성해서 각기 다른 type이 적용 될 수 있게 코드를 작성한다.
  - ~입력 값들이 비어 있을 경우 경고 구문 UI를 구별할 수 있게 props에 boolean을 추가한다.~
    - ~단, data에 해당 props를 연결할 필요는 없다.~ 
    - 추후 리액트를 본격화 할 때 작성할 예정
    - 경고 구문 UI의 css를 작성한다.

### ✏️Task
- [x] 내 근로 살펴보기(ViewMyWork) 페이지 html을 작성한다.
  - [x] 컴포넌트로 구성할 영역을 생각하고 컴포넌트로 나눈다.
    - [x] 재활용되는 컴포넌트 네이밍은 `component`라는 단수로 키워드를 넣어야한다. (ex. ViewMyWorkOption.component.jsx)
      - [x] option 영역
      - [x] input 영역
- [x] 내 근로 살펴보기(ViewMyWork) 페이지 css룰 작성한다.
- [x] component를 사용해서 영역을 분리한다.
  - [x] props를 사용해서 각기 다르게 코드를 구성할 수 있게 짠다.
  - [x] input 부분의 스타일이~ 삼항연산~ _(eslint 규칙에 의해 삼항연산 불가 이에 if문으로 변경)_ if문을 사용해서 전달받은 props에 따라 값이 UI가 동적으로 변할 수 있게 코드를 작성한다.
  - [x] 배열 객체를 생성해서 각기 다른 type이 적용 될 수 있게 코드를 작성한다.
  - ~[ ] 입력 값들이 비어 있을 경우 경고 구문 UI를 구별할 수 있게 props에 boolean을 추가한다.~
    - ~단, data에 해당 props를 연결할 필요는 없다.~ 
    - 추후 리액트를 본격화 할 때 작성할 예정
    - [x] 경고 구문 UI의 css를 작성한다.

### 🗓Next Task
-

**Comment by 4BFC** [comment]
@frombunny 컴포넌트로 분리되는 jsx는 위 이슈와 같이 작성하면 어떨까 합니다. 추가적으로 공통으로 사용되는 컴포넌트는 페이지명 없이 키워드 중심으로 생각했습니다. 예를들면 모든 페이지에서 공통으로 사용되는 button은 `Button.components.jsx`라고 작성하면 어떨까합니다. 그렇다면 Hedaer와 Footer는 `Header.component.jsx`, `Footer.component.jsx`이렇게 작성하게 되는데 이게 맞을까요? 다른 방법이나 더 좋은 직관적 네이밍 방식이 있다면 여기에 의견 남겨주세요.

**Comment by frombunny** [comment]
> @frombunny 컴포넌트로 분리되는 jsx는 위 이슈와 같이 작성하면 어떨까 합니다. 추가적으로 공통으로 사용되는 컴포넌트는 페이지명 없이 키워드 중심으로 생각했습니다. 예를들면 모든 페이지에서 공통으로 사용되는 button은 `Button.components.jsx`라고 작성하면 어떨까합니다. 그렇다면 Hedaer와 Footer는 `Header.component.jsx`, `Footer.component.jsx`이렇게 작성하게 되는데 이게 맞을까요? 다른 방법이나 더 좋은 직관적 네이밍 방식이 있다면 여기에 의견 남겨주세요.

충분히 직관적인 것 같습니다 😃 인지하고 작성하겠습니다!
