### ISSUE TITLE
API 통신을 위해 환경변수 설정을 한다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#33]
### ⚠️Issue
- API 통신을 위해 환경변수 설정을 한다.
> 해당 PR은 issue 번호 33에 40이 종속되어 있어 PR을 하나로 묶어 작성했습니다. 이점 양해주시고 참고해주시면 감사하겠습니다.

### ✏️Task
- [x] dotenv 라이브러리를 설치한다. 
- [x] Axios 라이브러리를 설치 한다.
- [x] `devDependencies`, `dependencies`에 설치해야하는 확인한다.
  - ~[ ] 각 API 환경 변수를 설정한다.~
    - ~[ ] 환경변수를 가져오는 방식 정한다.~
      - ~[ ] 객체 방식~
- [x] #40

### 🗓Next Task
- 설정된 env로 Axios model을 구성하고 구현한다.
- Moking으로 간단한 test를 진행할지 고려한다.
- #40
