### ISSUE TITLE
내 근로 현환 결과지(ViewMyWorkResult) 페이지 css를 작성한다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#39]
### ⚠️Issue
- 내 근로 현환 결과지(ViewMyWorkResult) 페이지 css를 작성한다.

### ✏️Task
- [x] 내 근로 현환 결과지(ViewMyWorkResult) 페이지 css를 작성한다.
  - [x] common 디렉토리를 생성한다.
    - 📌Global과 Common의 차이가 있는가? 공통으로 다루어야 하는 디렉토리의 네이밍을 정할 필요가 있음
    - [x] 재활용할 수 있는 컴포넌트를 생성한다.
    -  ~-  ViewMyWorkResult.component.jsx라고 네이밍은 지었으나 어떤 영역인지 명확하지는 않다. 물론, 필요 컴포넌트에서 불러와 사용할 때는 변수로 재할당 후 사용을 하겠지만 `ViewMyWorkResult.jsx`와 차별점, 정체성이 크게 들어나지 않고 있다. 아래 예시로 들여다보면 다음과 같다.~
    ~import ViewMyWorkResult from '../(Common || Global)/components/ViewMyWorkResult.component.jsx~
       ~// 물론, 여기서 `ViewMyWorkResult.jsx` 컴포넌트에선 error를 발생 시킬 것이다.~
      ~const Result = ViewMyWorkResult;~
  - [x] ViewMyWorkResult의 Result 영역의 option들의 요소들을 컴포넌트로 분리 한다.
    -  API의 데이터 형태에 따라 판단할 필요가 있다.
        - API 결과지 상세 조회 response(200) 값
            ```
              {
                  "status" : 200,
                  "data" : {
	                  "nickname" : "코카콜라",
	                  "title" : "미도인 성수",
	                  "content" : "코카콜라님은~~",
	                  "extra_pay" : true, // 가산 수당 발생 여부
	                  "week_pay" : false, // 주휴 수당 발생 여부
	                  "night_pay" : true, // 야간 수당 발생 여부
	                  "overtime_pay" : false, // 연장 근로 수당 발생 여부
	                  "holiday_pay" : true // 휴일 근로 수당 발생 여부
                  },
                  "message" : "근로 결과지 세부 조회 완료되었습니다."
              }
            ```
          - [x] 추후에 API를 통해 데이터를 가져올 때 '.'을 기준으로 map과 split을 사용해서 2차적인 가공이 필요하다.
          - [x] 추후에 API를 통해 데이터를 가져올 때 '코카콜라'를 replace로 `${nickname}`으로 변환하는 가공이 필요하다.
  - [x] data로 각 정보들을 분리할지 검토한다.
       📌 결론: 필요하다. 이를 통해서 API가 어떻게 값을 가져오게 될지 미리 검토하고 각 컴포넌트의 구성 요소들이 달라지기 때문이다.
- [x] 브라우저에서 화면 축소를 하게 되면 footer 영역이 하단으로 고정이 안되어 있음. 검토 필요
- [x] #41
### 🗓Next Task
-
