### ISSUE TITLE
API 통신을 위한 전역 함수를 설정 한다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#40]
### ⚠️Issue
- API 통신을 위한 전역 함수를 설정 한다.
> 해당 PR은 issue 번호 33에 40이 종속되어 있어 PR을 하나로 묶어 작성했습니다. 이점 양해주시고 참고해주시면 감사하겠습니다.
### ✏️Task
- ~[x] Axios를 설치 한다.~ #33 
- [x] Axois로 인스턴스를 함수를 생성한다.
  - [x] 유지 보수, 가독성을 위해 useEffect를 사용해서 커스텀 Hook을 제작한다.
    - [x] try, catch로 예외처리를 관리한다.
    - [x] async, awiat으로 비동기로 API를 처리한다.
    - [x] 커스텀 훅을 재사용할 수 있게 props를 어떻게 구현해야할지, return과 export를 고민한다.
- [x] 생성한 함수와 커스텀 훅을 테스트하기 위한 모킹을 구현한다.
  - [x] 기존 로컬로 제작한 data.js를 json형태로 수정 및 가공한다.
  - [x] 병렬 방식 mocking이 아닌 직렬 방식 mocking으로 우선 구현한다.

### 🗓Next Task
- 현재까지의 작업들을 모두 develop 브런치로 통합하고 확인 및 footer와 header를 설정한다. 더해서 js-doc을 설정해서 리팩토링한다.
