### ISSUE TITLE
VmwrResult 컴포넌트의 Props를 재설정 및 검토한다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#41]
### ⚠️Issue
- VmwrResult 컴포넌트의 Props를 ViewMyWorkResult에서 data로 가져올 수 있게 재설정 및 검토한다.
- #43 
- #44 

### ✏️Task
- [x] VmwrResult 컴포넌트의 Props를 ViewMyWorkResult에서 data로 가져올 수 있게 재설정 및 검토한다.
  - [x] 리팩토링한 prop-types의 정의 방식을 설명한다.
  - [x] 재활용을 위해서 해당 컨텐츠만 내용을 추출할 수 있게 css 분리
- [x] FetachAPI custom hook을 사용해서 필요한 곳에 적용해본다.
- [x] Mocking을 통해서 data를 가지고 온다.
- [x] Js-doc를 설치한다.
  - [x] 하위 컴포넌트의 Prop-Type을 활용해서 js-doc으로 리팩토링한다.
### 🗓Next Task
-

**Comment by 4BFC** [comment]
@nyun-nye 요청하신 부분 수정 했습니다. tracking 해서 확인하시고 급하시면 pull로 받아와서 작업하시면 될 듯합니다. 금일 안으로 해당 이슈 완료 예정입니다.
