### ISSUE TITLE
develop 브런치를 점검하고 모든 페이지에서 기능들을 점검한다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#44]
## ⚠️Issue
- develop 브런치를 점검하고 Header와 Footer를 모든 페이지에 적용한다.
- ~Js-doc를 설치한다.~
> Axios, Mocking 설정까지 모두 마친 후 진행되는 검토 과정입니다. 중간 점검 및 검토라고 생각하시면 됩니다.
> 해당 issue는 branch와는 무관합니다. 해당 issue는 여러 issue로 분리됨에 따라 `issue`와 subTask는 일부는 Legacy 입니다. 연관 issue는 다음과 같습니다.

- #23  
- #31  
- #40 
- #45 
---
## ✏️Task
- [x] develop 브런치를 점검하고 Header와 Footer를 모든 페이지에 적용한다.
- ~[ ] FetachAPI custom hook을 사용해서 필요한 곳에 적용해본다.~
- ~[x] Js-doc를 설치한다.~
  - ~[ ] 하위 컴포넌트의 Prop-Type을 활용해서 js-doc으로 리팩토링한다.(9/29)~ 
  > 해당 sub task는 #41 에서 수행할 예정입니다.
- [x] Header, Footer 적용 및 점검
- [ ] 모든 페이지를 점검하고 기능들과 리팩토링 및 코드 수정이 필요한 부분들을 점검한다. (10/5 - 최종 점검)
  - 점검 대상
    - 함수
    - 컴포넌트
    - 네이밍
    - 라이브러리
    - 디렉토리구조
- [x] #45 (9/28)
- [x] #23 (9/28)

## 🗓Next Task
-

**Comment by 4BFC** [comment]
@frombunny 해당 issue와 해당 subTask는 일부 Legacy입니다. 참고 바랍니다.

**Comment by 4BFC** [comment]
@frombunny @nyun-nye 해당 부분은 5일 회의 중 별도로 간단하게 점검하고 넘어갈 예정입니다.

**Comment by 4BFC** [comment]
- Author 제거 방법
  ```
    git filter-branch --commit-filter '
        if [ "$GIT_AUTHOR_NAME" = "Author-name" ] || [ "$GIT_AUTHOR_NAME" = "Author-name2" ]; then
            skip_commit "$@";
        else
            git commit-tree "$@";
        fi' -- --all
  ```
- 특정 Author commit 내역확인 
  ```
    git log --author="Author commit"
  ```

- 해당 코드를 사용할 시 pr과 issue가 엉킬수 있습니다. 영향력이 없는 issue 또는 pr에 해당하에 위의 명령을 시도합니다.
- 또 다른 방법으로는 `git filter-repo`와 같은 기능을 사용할 수 있습니다.
  - 해당 작업은 새로 clone을 받은 후에 작업을 할수 있기 때문에 특정 분기에서 작업을 해야 정상적으로 동작합니다.
- 🔗[remove Author](https://creative103.tistory.com/149)
