### ISSUE TITLE
Mocking 환경을 구축한다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#45]
### ⚠️Issue
- Mocking 환경을 구축한다.(9/29)

### ✏️Task
- [x] json-server로 Mocking 환경을 구축한다.
  - [x] 관련 ~.data.js를 json으로 가공한다.
  - [x] fetchAPI 작업을 마무리한다.
  - [x] fetchAPI를 가지고 custom Hook을 제작한다.
    - [x] 생성한 custom Hook을 테스트해보고 점검해본다.
    - [x] Mocking API 주소를 dotenv에 적용해고 FetchAPI에 적용한다.

### 🗓Next Task
-

**Comment by 4BFC** [comment]
📝Reports
- useFetchAPI로 리팩토링하기 전 일반 Fetch.instance.js만을 사용한 예시
  ```
    import React, { useEffect } from 'react';
    import { getData } from '../../../Global/API/fetch.instance';
    
    const DevMockingApi = () => {
      useEffect(() => {
        const FetchData = async () => {
          try {
            const data = await getData('/results');
            console.log(data);
          } catch (error) {
            console.error('API Error : ', error);
          }
        };
        FetchData();
      }, []);
    
      return <div>Mocking Test Page</div>;
    };
    
    export default DevMockingApi;
  ```

**Comment by 4BFC** [comment]
- 환경 변수 설정(.env)
  - 환경 변수 설정 후 실행되고 있는 모든 서버를 재시작해야 적용이 된다.
```
  # Clinet
  # Elements
  API_KEY=your_api_key
  DB_HOST=localhost
  DB_USER=root
  DB_PASSWORD=your_password
  PORT=3000
  MOCKING=3001
  
  # protocal URL
  REACT_APP_MOCKING_API_URL=http://localhost:3001
```
