### ISSUE TITLE
게시글 작성(QnAPosting)페이지 css를 작성한다.

### ISSUE THREAD

**Issue by nyun-nye** [HSU-Likelion12-yourSide/YourSide-Front#50]
### ⚠️Issue
- 게시글 작성(QnAPosting)페이지 css를 작성한다.
> 해당 issue는 Legacy이므로 issue #66 으로 넘어갑니다.

### ✏️Task
- [x] 게시글 작성 페이지 css를 작성한다.
- [x] 기존에 작성되어 있던 Header와 Footer를 활용하여 페이지 디자인을 작성한다.
- [x] ViewMyWorkResult 컴포넌트를 활용하여 내 결과지 가져오기의 디자인을 구현한다.

### 🗓Next Task
 - [x] #66
