### ISSUE TITLE
각 페이지에 필요한 모달창을 구현한다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#52]
### ⚠️Issue
- 각 페이지에 필요한 모달창을 구현한다.
> 모달창 관련 라이브러리를 사용하지 않는다.
> dialog 태그를 사용하지 않는다.
> ViewMyWork를 기준으로 모달창 구현

### ✏️Task
- [x] 각 페이지에 필요한 모달창을 구현한다.
  - ~[ ] 해당 모달창은 props를 최대한 활용해서 개발자가 원하는 HTML 내에 문자로 입력할 수 있게 구현한다.~
  - [x] 모달창이 활성화되면 Scroll 비활성화
  - [x] 모달창 제외 다른 페이지 클릭시 모달창 비활성화
  - [x] 상황에 따른 모달창 Type 변화 로직 구현
    - [x] ContextAPI 사용(useGlobalState)
  - [x] ViewMyResult 모달창
  - [x] Login 모달창
  - [x] SginUp 모달창
  > 단, ViewMyWorkResult와 관련 된 모달창은 제외이다.

### 🗓Next Task
-
