### ISSUE TITLE
페이지를 연결하고 Alert를 활용해서 미완성 부분을 표기 한다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#54]
### ⚠️Issue
- 페이지를 연결하고 Alert를 활용해서 미완성 부분을 표기 한다.
- 컴포넌트를 분리하고 API로 가져와 삽입할 영역을 템플릿 리터럴로 표기 및 구현한다.

### ✏️Task
- [x] 페이지를 Link로 연결하고 Alert를 활용해서 미완성 부분을 표기 한다.
- [x] 컴포넌트를 나눈다.
  - [x] ViewQuestionAndAnswer: comment
  - [x] QuestionAndAnswer: list
- [x] 버튼 영역에 :focus를 적용한다.
  - [x] 클릭했을 때 hover되는 부분 image를 클릭된 이미지로 적용할 수 있게 한다.
    - [x] bookmark
      - [x] 삼항연산을 통해서 상태 값에 따른 id 또는 className으로 컨트롤
    - [x] like,bad button 등록,해지
      - [x] bookmark와 이하 동일
    - [x] qa-group/qa-box
### 🗓Next Task
-

**Comment by 4BFC** [comment]
- 리펙토링 필요 부분
  - Question.jsx|scss - wdith, padding, margin 구분 필요
  - RankQuestion.jsx|scss - wdith, padding, margin 구분 필요
  - Login.jsx - max-width
  - Notaion.jsx - max-width
  - NotaionExample.jsx - max-width
---
- 페이지 미완성 부분
  - 게시글 작성( #50 ) 
  - 다른 결과지(UsersWorkResult || List.jsx) - 네이밍 변경 필요
    - 해당 페이지는 목록화 연결 완성 후 작업 진행 예정
  - 마이페이지(MyPage.jsx) - 후 순위
  - 아이디 찾기(FindID.jsx) - 후 순위
  - 비밀번호 찾기(FindPW.jsx) - 후 순위
---
- 주의 사항
  - WorkArrangement 페이지에서 `상세보기` 버튼 클릭시 ViewMyWorkResult로 넘어간다. 상세 내용은 alert 참조
  - RankQuestion 페이지에서 해당 게시물 클릭시 ViewQuestionAndAnswer로 넘어간다. 상세 내용은 alert 참조
  - Question 페이지에서 해당 게시물 클릭시 ViewQuestionAndAnswer로 넘어간다. 상세 내용은 alert 참조
---
- 페이지가 넘어간 후 viewport가 상단으로 올라가지 않는다. 이 부분 issue는 후순위에 둔다.
- 데모버전 출시 후 렌도링 최적화 하는 방법을 찾아보고 이를 적용할 방법을 고민한다.
 🔗[리액트 렌더링 최적화 방법](https://nayoungkim00.tistory.com/18 "렌더링 최적화 방법")
