### ISSUE TITLE
API 연동을 위해 환경설정을 점검한다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#55]
### ⚠️Issue
- API 연동을 위해 환경설정을 점검한다.

### ✏️Task
- [x] .env 파일 수정
- [x] Postman 확인
- [x] API 연동 및 데이터를 가지고 오는 페이지를 생성한다.
- [x] API 작업 순서를 정한다.
  - [x] 목록화를 먼저 가지고 온다.
    - [x] ~목록화의 id를 가지고올 globalState를 구현한다.~

### 🗓Next Task
-
