### ISSUE TITLE
ViewQuestionAndAnswer 부분을 리팩토링한다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#57]
### ⚠️Issue
- ViewQuestionAndAnswer 부분을 리팩토링한다.

### ✏️Task
- [x] 레이아웃을 수정한다.
- [x] padding 간경을 준다.
- [x] margin 간격을 준다.
- [x] vmwrResult 부분의 모킹을 확인하고 ~배열로~ 데이터를 받아오는지 다시 확인한다.

### 🗓Next Task
-
