### ISSUE TITLE
네편현답(QuestionAndAnswer) 페이지의 질문 목록 API를 연결한다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#61]
### ⚠️Issue
- 네편현답 페이지의 질문 목록 API를 연결한다.

### ✏️Task
- [x] 게시글 전체 조회 API 연결
  - [x] ~Promise.all을 사용해서 병렬도 두개의 API를 호출 할 수 있게 한다.~
  - > 이를 사용하기 위해서는 useFetchAPI를 수정해야한다. 이는 시간의 제약으로 제외한다.
    <details>
      <summary>Promise.all</summary>
        ```
        useEffect(() => {
            const fetchData = async () => {
              setIsLoading(true);
              setIsError(null);
              
              try {
                const [postsResponse, popularResponse] = await Promise.all([
                  fetch(`https://yourapi.com/posting/list/${isType}`).then(res => res.json()),
                  fetch(`https://yourapi.com/posting/list/popular/${isType}`).then(res => res.json())
                ]);
                
                // 일반 게시글과 인기 게시글 데이터 설정
                setPosts(postsResponse.data);
                setPopularPosts(popularResponse.data);
              } catch (error) {
                setIsError(error);
              } finally {
                setIsLoading(false);
              }
            };
        
            fetchData();
          }, [isType]);
        ```
    </details>
- [x] 인기 게시글 조회

### 🗓Next Task
- [x] #63
  - QuestionAndAnswer를 클릭하면 반환되는 특정 id 값을 useGlobalState 변수로 컨트롤 한다.

**Comment by 4BFC** [comment]
- popular api에 id가 필요
- isLoading, isError에 따른 디자인이 필요
- useFetchAPI를 Promise.all을 사용해서 리팩토링이 필요
- 나눈 컴폰너트의 jsdoc 적용 -> 프로젝트가 끝나고 이를 통해서 문서화
