### ISSUE TITLE
네편현답 상세 보기 (ViewQuestionAndAnswer) 페이지와 근로지 결과(VmwrResult) API를 연결한다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#63]
### ⚠️Issue
- 네편현답 상세 보기 (ViewQuestionAndAnswer) 페이지와 근로지 결과(VmwrResult) API를 연결한다.
  - ViewQuestionAndAnswer.jsx
  - QuestionAndAnswer.jsx
  - Question.jsx
  - VmwrResults.component.jsx

### ✏️Task
- [x] 상세 보기 API 연결
- [x] API에 데이터 검증을 설계한다.(작성 후 논의 필요)
- [x] 새로고침 시 데이터 손실 방안 필요
  - [x] 해당 페이지 상세보기 특정 URI를 표기한다.
    - [x] App.jsx 동적 경로로 변경 ~-> 백엔드와 협의 필요~
      - [x] useParams를 통해서 값을 가지고 오려고 했으나 문제 발생
      - [x] URI 통해서 id 값 추출
        <details>
              <summary>CORS 정책 위반 Error</summary>
                        Access to XMLHttpRequest at 'http://13.124.144.93:8080/api/posting/[object%20Object]' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.Understand this error
                        13.124.144.93:8080/api/posting/[object%20Object]:1 
                         Failed to load resource: net::ERR_FAILED
      </details>

### 🗓Next Task
- [x] #64
  - bookmark 상태값에 따른 기능 구현 post 구현 필요
