### ISSUE TITLE
네편현답 상세 보기 (ViewQuestionAndAnswer) 페이지 컴포넌트 분리와 코멘트 API를 연결한다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#64]
### ⚠️Issue
- 네편현답 상세 보기 (ViewQuestionAndAnswer) 페이지 컴포넌트 분리와 코멘트 API를 연결한다.
  - 

### ✏️Task
  - [x] bookmark 상태값에 따른 기능 구현 post 구현
  - [x] 코멘트를 컴포넌트로 분리한다.
  - [x] post 코멘트를 연결한다.
    - [x] 좋아요 싫어요 post 완료
    - [x] 댓글달기 완료
  - [x] get 부분의 백엔드와 논의

### 🗓Next Task
- [x] #70

**Comment by 4BFC** [comment]
- get으로 requestBody를 요청할 수 있다.
- [get requestBody](https://funveloper.tistory.com/157 'get requestBody')
