### ISSUE TITLE
게시글 작성(PostingQnA)페이지 css 작업을 마무리한다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#66]
### ⚠️Issue
- 게시글 작성(PostingQnA)페이지 css 작업을 마무리한다.
> 해당 issue는 #50 작업을 이어하는 task 입니다.

### ✏️Task
- [x] QnAPosting 페이지를 PostingQnA로 리네이밍한다.
- [x] 필요한 모달창을 구현한다.
  - [x] 모달창이 서로 연결되게 구현한다.

### 🗓Next Task
 -
