### ISSUE TITLE
공지사항(Notice) 페이지의 기능 구현과 API 통신을 한다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#75]
### ⚠️Issue
- 공지사항(Notice) 페이지의 기능을 구현한다.

### ✏️Task
- [x] 공지사항(Notice) css를 리팩토링 한다.
- [x] 공지사항(Notice) API를 연결한다.
- [x] ~공지사항(Notice) 페이지의 기능을 구현한다.~
  - 더미데이터 구현 후 작업 예정

### 🗓Next Task
-
