### ISSUE TITLE
배포를 위해 업데이트를 한다.

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#98]
### ⚠️Issue
- 배포를 위해 업데이트를 한다.

### ✏️Task
- [x] ver.1.0.0을 배포를 한다.
- [x] ver.1.0.1을 배포를 한다.
- [ ] ver.2.0.0을 배포를 한다.

### 🗓Next Task
-
